module.exports = {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    container: {
      center: 'true',
  },
  screens: {
      sm: '640px', // landscape mobile
      md: '768px', // tablet
      lg: '1024px', // laptop
      xl: '1260px', // desktop
      xxl: '1440px',
      print: { raw: 'print' },
  },
  colors: {
      transparent: 'transparent',
      black: 'black',
      white: '#fff',
      primary: {
          DEFAULT: 'var(--primary)',
          light: 'var(--primary-light)',
          lighter: 'var(--primary-lighter)',
          lightest: 'var(--primary-lightest)',
          dark: 'var(--primary-dark)',
          darker: 'var(--primary-darker)',       
          darkest: 'var(--primary-darkest)',
      },
      honey: {
          DEFAULT: 'var(--honey)',
          light: 'var(--honey-light)',
          lighter: 'var(--honey-lighter)',
          lightest: 'var(--honey-lightest)',
          dark: 'var(--honey-dark)',
          darker: 'var(--honey-darker)',       
          darkest: 'var(--honey-darkest)',
      },
      gray: {
          DEFAULT: 'var(--gray)',
          light: 'var(--gray-light)',
          lighter: '#bbbbbb',
          lightest: 'var(--gray-lightest)',
          dark: 'var(--gray-dark)',
      },
      orange: {
          DEFAULT: 'var(--orange)',
          dark: 'var(--orange-dark)',
      },
      ink: 'var(--ink)',
      alternative: {
          DEFAULT: 'var(--alternative)',
          text: 'var(--alternative-text)',
      },
      highlight: {
          DEFAULT: 'var(--highlight)',
          dark: 'var(--highlight-dark)',
      },
      border: {
          DEFAULT: 'var(--border)',
          light: 'var(--border-light)',
      },
      blue: 'var(--blue)',
      'red': '#FF0000',
      secondary: 'var(--secondary)',
      tertiary: 'var(--tertiary)',
      quaternary: 'var(--quaternary)',
      tagline: 'var(--tagline)',
      social: 'var(--social)',
      success: {
          DEFAULT: 'var(--success)',
          darker: 'var(--success-darker)'
      },
      error: {
          DEFAULT: 'var(--error)',
          light: 'var(--error-light)',
          dark: 'var(--error-dark)'
      },
      facebook: 'var(--facebook)',
      'google': '#4284f4',
      twitter: 'var(--twitter)',
  },
  fontSize: {
      tiny: '12px',
      small: '14px',
      base: '16px',
      h6: '18px',
      h5: '20px',
      h4: '22px',
      h3: '26px',
      h2: '30px',
      h1: '36px',
      huge: '46px',
  },
  lineHeight: {
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
      3: '.75rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      7: '1.75rem',
      8: '2rem',
      9: '2.25rem',
      10: '2.5rem',
  },
  borderColor: theme => ({
      ...theme('colors'),
      DEFAULT: theme('colors.border.DEFAULT', 'currentColor'),
  }),
  inset: {
      0: 0,
      auto: 'auto',
      '1/2': '50%',
      full: '100%',
  },
  spacing: theme => ({
      px: '1px',
      0: '0',
      2: '2px',
      3: '3px',
      4: '4px',
      5: '5px',
      6: '6px',
      7: '7px',
      8: '8px',
      9: '9px',
      10: '10px',
      12: '12px',
      14: '14px',
      15: '15px',
      16: '16px',
      18: '18px',
      20: '20px',
      24: '24px',
      25: '25px',
      30: '30px',
      35: '35px',
      40: '40px',
      45: '45px',
      50: '50px',
      55: '55px',
      60: '60px',
      70: '70px',
      80: '80px',
      90: '90px',
      100: '100px',
      120: '120px',
      130: '130px',
      150: '150px',
      200: '200px',
      250: '250px',
      300: '300px',
      400: '400px',
      500: '500px',
      '80vh': '80vh',
      ...theme('screens'),
  }),
  minWidth: theme => theme('width'),
  maxWidth: theme => theme('width'),
  maxHeight: theme => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh',
      '50vh': '50vh',
  }),
  borderRadius: {
      none: '0',
      sm: '2px',
      DEFAULT: '3px',
      md: '6px',
      lg: '8px',
      xl: '10px',
      full: '9999px',
  },
  zIndex: {
      auto: 'auto',
      0: '0',
      10: '10',
      20: '20',
      30: '30',
      40: '40',
      50: '50',
      60: '60',
      70: '70',
      80: '80',
      90: '90',
      100: '100',
      999: '999',
  },

    extend: {},
  },
  plugins: [],
}
